#!/bin/bash

KEYLENGTH=$1

if [ "$KEYLENGTH" = "" ]; then KEYLENGTH=4096; fi

if [ -e signing.key -o -e signing.crt ]; then
    echo "Refusing to run because there's already a key or cert here."
    exit 1
fi

unalias rm 2>/dev/null

openssl req -newkey ec:<(openssl ecparam -name secp521r1) -keyout signing.key.enc -out signing.req -subj "/C=GO/ST=reign/CN=Reign Signing Certificate/" -passout pass:abcd &&\
openssl ec -in signing.key.enc -out signing.key -passin pass:abcd && \
rm -f signing.key.enc && \
openssl x509 -req -days 3650 -in signing.req -signkey signing.key -out signing.crt && \
rm -f signing.req