#!/bin/bash

# The tests use underscores in some variable names... golint false-flags them.
GOLINTOUT=$(golint *go | grep -v underscores)

if [ ! -z "$GOLINTOUT" -o "$?" != 0 ]; then
    echo golint failed:
    echo $GOLINTOUT
    exit 1
fi

go test

